/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bicis.test.ui.UI;

import bicis.test.ui.Producto;
import bicis.test.ui.Utilidades;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author gabob
 */
public class RegistroDeProductos extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */

    public RegistroDeProductos() {
        initComponents();
        
        //El array de los JLabels
        JLabel[] labels = {LogoCicloTEC, ProductosLogo,FondoCodigoPrincipal,
        FondoCodigoPrincipal,FondoTamaño,FondoMarca,FondoPrecio,FondoCantidad, 
        FondoCodigoArticulo, FondoNombreArticulo};
        
        //Ponerle color JLabel del fondo (Gris Oscuro)
        Color col = new Color(152, 151, 153);
        getContentPane().setBackground(col);
        
        //Nuevo código para ajustar muchos JLabels usando arrays!
        for (JLabel label : labels){
            Utilidades.imageStretcher(label);
        }
        
        //Activar esta línea hasta el final
        Utilidades.setCustomIcon(this, "images/CicloTEC Logo.png");
        
        limpiarCampos();
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        LogoCicloTEC = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        Productos = new javax.swing.JLabel();
        ProductosLogo = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();
        LineaHorizontal1 = new javax.swing.JLabel();
        LineaHorizontal2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Codigo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        CodigoArticulo = new javax.swing.JLabel();
        NombreArticulo = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Tamaño = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        TextFieldCodigoArticulo = new javax.swing.JTextField();
        TextFieldNombreArticulo = new javax.swing.JTextField();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        TextFieldTamaño = new javax.swing.JTextField();
        TextFieldMarca = new javax.swing.JTextField();
        TextFieldPrecio = new javax.swing.JTextField();
        TextFieldCodigoPrincipal = new javax.swing.JTextField();
        FondoCodigoPrincipal = new javax.swing.JLabel();
        FondoCodigoArticulo = new javax.swing.JLabel();
        FondoNombreArticulo = new javax.swing.JLabel();
        FondoTamaño = new javax.swing.JLabel();
        FondoMarca = new javax.swing.JLabel();
        FondoPrecio = new javax.swing.JLabel();
        TextFieldCantidad = new javax.swing.JTextField();
        TextFieldNombre = new javax.swing.JTextField();
        FondoCantidad = new javax.swing.JLabel();
        FondoNombre1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Productos - CicloTEC");
        setMinimumSize(new java.awt.Dimension(690, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoCicloTEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CicloTEC (Tienda).png"))); // NOI18N
        LogoCicloTEC.setText("jLabel4");
        getContentPane().add(LogoCicloTEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 100));

        Registro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        Registro.setForeground(new java.awt.Color(51, 51, 51));
        Registro.setText("Registro de");
        getContentPane().add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        Productos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        Productos.setForeground(new java.awt.Color(51, 51, 51));
        Productos.setText("Productos");
        getContentPane().add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        ProductosLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Productos.png"))); // NOI18N
        getContentPane().add(ProductosLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 60));

        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Vertical.png"))); // NOI18N
        getContentPane().add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 10, 390));

        LineaHorizontal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Horizontal.png"))); // NOI18N
        getContentPane().add(LineaHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, -1));

        LineaHorizontal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Horizontal.png"))); // NOI18N
        getContentPane().add(LineaHorizontal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        Back.setBackground(new java.awt.Color(217, 217, 217));
        Back.setForeground(new java.awt.Color(51, 51, 51));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrow Curved - Left.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 50, 50));

        Buscar.setBackground(new java.awt.Color(217, 217, 217));
        Buscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Buscar.setForeground(new java.awt.Color(51, 51, 51));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 120, 30));

        Agregar.setBackground(new java.awt.Color(217, 217, 217));
        Agregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Agregar.setForeground(new java.awt.Color(51, 51, 51));
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 120, 30));

        Eliminar.setBackground(new java.awt.Color(217, 217, 217));
        Eliminar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(81, 18, 18));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 120, 30));

        Modificar.setBackground(new java.awt.Color(217, 217, 217));
        Modificar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Modificar.setForeground(new java.awt.Color(51, 51, 51));
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 120, 30));

        Codigo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Codigo.setForeground(new java.awt.Color(51, 51, 51));
        Codigo.setText("Código:");
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 7, -1, 40));

        Nombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setText("Nombre:");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        CodigoArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        CodigoArticulo.setForeground(new java.awt.Color(51, 51, 51));
        CodigoArticulo.setText("Código Artículo:");
        getContentPane().add(CodigoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        NombreArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        NombreArticulo.setForeground(new java.awt.Color(51, 51, 51));
        NombreArticulo.setText("Nombre Artículo:");
        getContentPane().add(NombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        Tipo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Tipo.setForeground(new java.awt.Color(51, 51, 51));
        Tipo.setText("Tipo:");
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        Tamaño.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Tamaño.setForeground(new java.awt.Color(51, 51, 51));
        Tamaño.setText("Tamaño:");
        getContentPane().add(Tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        Marca.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Marca.setForeground(new java.awt.Color(51, 51, 51));
        Marca.setText("Marca:");
        getContentPane().add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        Precio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Precio.setForeground(new java.awt.Color(51, 51, 51));
        Precio.setText("Precio:");
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        Cantidad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(51, 51, 51));
        Cantidad.setText("Cantidad:");
        getContentPane().add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 30));

        TextFieldCodigoArticulo.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldCodigoArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldCodigoArticulo.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldCodigoArticulo.setBorder(null);
        TextFieldCodigoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodigoArticuloActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldCodigoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 250, 20));

        TextFieldNombreArticulo.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldNombreArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldNombreArticulo.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldNombreArticulo.setBorder(null);
        TextFieldNombreArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreArticuloActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 240, 20));

        ComboBoxTipo.setBackground(new java.awt.Color(217, 217, 217));
        ComboBoxTipo.setForeground(new java.awt.Color(51, 51, 51));
        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicicleta", "Accesorios", "Suplementos" }));
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 370, -1));

        TextFieldTamaño.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldTamaño.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldTamaño.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldTamaño.setBorder(null);
        getContentPane().add(TextFieldTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 320, 20));

        TextFieldMarca.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldMarca.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldMarca.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldMarca.setBorder(null);
        getContentPane().add(TextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 330, 20));

        TextFieldPrecio.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldPrecio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldPrecio.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldPrecio.setBorder(null);
        getContentPane().add(TextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 330, 20));

        TextFieldCodigoPrincipal.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldCodigoPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldCodigoPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldCodigoPrincipal.setBorder(null);
        TextFieldCodigoPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodigoPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldCodigoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 280, 20));

        FondoCodigoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoCodigoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 290, 30));

        FondoCodigoArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoCodigoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 270, 30));

        FondoNombreArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 260, 30));

        FondoTamaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 340, 30));

        FondoMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 350, 30));

        FondoPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 350, 30));

        TextFieldCantidad.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldCantidad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldCantidad.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldCantidad.setBorder(null);
        TextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 310, 20));

        TextFieldNombre.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldNombre.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldNombre.setBorder(null);
        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 310, 20));

        FondoCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 330, 40));

        FondoNombre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        MenuPrincipal jfmain = new MenuPrincipal();
        jfmain.show(); //Mostrar MenuPrincipal
        dispose(); //Cerrar RegistroDeProductos
    }//GEN-LAST:event_BackActionPerformed
  
    private void limpiarCampos() {
        TextFieldCodigoPrincipal.setText("");
        TextFieldNombre.setText("");
        TextFieldCodigoArticulo.setText("");
        TextFieldNombreArticulo.setText("");
        TextFieldMarca.setText("");
        TextFieldPrecio.setText("");
        TextFieldCantidad.setText("");
        ComboBoxTipo.setSelectedIndex(0);
    }
    
    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try {
            int codigo = Integer.parseInt(TextFieldCodigoPrincipal.getText());

            // confirmacion
            int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Esta seguro de que desea eliminar el producto con código " + codigo + "?", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION);

            // Verificacion
            if (confirmacion == JOptionPane.YES_OPTION) {
                Producto.eliminarProducto(codigo);
                JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Se cancelo la operacion.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar producto: " + e.getMessage());
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        try {
            int codigo = Integer.parseInt(TextFieldCodigoPrincipal.getText());
            String nombre = TextFieldNombre.getText();
            int codigoArticulo = Integer.parseInt(TextFieldCodigoArticulo.getText());;
            String nombreArticulo = TextFieldNombreArticulo.getText();
            String marca = TextFieldMarca.getText();
            int precio = Integer.parseInt(TextFieldPrecio.getText());
            int cantidad = Integer.parseInt(TextFieldCantidad.getText());
            Producto.TipoProducto tipo = Producto.TipoProducto.valueOf(ComboBoxTipo.getSelectedItem().toString().toUpperCase());

            Producto.modificarProducto(codigo, nombre, codigoArticulo, nombreArticulo, marca, precio, cantidad, tipo);

            JOptionPane.showMessageDialog(this, "Producto modificado correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar producto: " + e.getMessage());
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

    private void TextFieldCodigoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodigoArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodigoArticuloActionPerformed

    private void TextFieldNombreArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreArticuloActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
    try {  
        if (!TextFieldCodigoPrincipal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "El campo de código no debe tener un valor al agregar un producto. Se genera automáticamente.",
                "Error en el código",
                JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }
        // Genera el código automáticamente
        int codigo = Producto.generarCodigoProducto();
        // Leer valores
        String nombre = TextFieldNombre.getText();
        int codigoArticulo = Integer.parseInt(TextFieldCodigoArticulo.getText());
        String nombreArticulo = TextFieldNombreArticulo.getText();
        String marca = TextFieldMarca.getText();
        int precio = Integer.parseInt(TextFieldPrecio.getText());
        int cantidad = Integer.parseInt(TextFieldCantidad.getText());
        Producto.TipoProducto tipo = Producto.TipoProducto.valueOf(ComboBoxTipo.getSelectedItem().toString().toUpperCase());

        // Crea un nuevo producto y lo agrega a la lista
        Producto nuevoProducto = new Producto(codigo, nombre, codigoArticulo, nombreArticulo, marca, precio, cantidad, tipo);
        Producto.agregarProducto(nuevoProducto);
        JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");
        limpiarCampos();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al agregar producto: ");
    }
    }//GEN-LAST:event_AgregarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        try {
            int codigo = Integer.parseInt(TextFieldCodigoPrincipal.getText());
            Producto producto = Producto.buscarProducto(codigo, "");
    
            if (producto != null) {
                TextFieldNombre.setText(producto.getNombreProducto());
                TextFieldCodigoArticulo.setText(String.valueOf(producto.getCodigoArticulo()));
                TextFieldNombreArticulo.setText(producto.getNombreArticulo());
                TextFieldMarca.setText(producto.getMarcaProducto());
                TextFieldPrecio.setText(String.valueOf(producto.getPrecio()));
                TextFieldCantidad.setText(String.valueOf(producto.getCantidad()));
                ComboBoxTipo.setSelectedItem(producto.getTipoproducto().toString());
                JOptionPane.showMessageDialog(this, "Producto encontrado.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar producto: ");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldCodigoPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodigoPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodigoPrincipalActionPerformed

    private void TextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Back;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel CodigoArticulo;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel FondoCantidad;
    private javax.swing.JLabel FondoCodigoArticulo;
    private javax.swing.JLabel FondoCodigoPrincipal;
    private javax.swing.JLabel FondoMarca;
    private javax.swing.JLabel FondoNombre1;
    private javax.swing.JLabel FondoNombreArticulo;
    private javax.swing.JLabel FondoPrecio;
    private javax.swing.JLabel FondoTamaño;
    private javax.swing.JLabel Linea;
    private javax.swing.JLabel LineaHorizontal1;
    private javax.swing.JLabel LineaHorizontal2;
    private javax.swing.JLabel LogoCicloTEC;
    private javax.swing.JLabel Marca;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreArticulo;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Productos;
    private javax.swing.JLabel ProductosLogo;
    private javax.swing.JLabel Registro;
    private javax.swing.JLabel Tamaño;
    private javax.swing.JTextField TextFieldCantidad;
    private javax.swing.JTextField TextFieldCodigoArticulo;
    private javax.swing.JTextField TextFieldCodigoPrincipal;
    private javax.swing.JTextField TextFieldMarca;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldNombreArticulo;
    private javax.swing.JTextField TextFieldPrecio;
    private javax.swing.JTextField TextFieldTamaño;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
