/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bicis.test.ui;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author gabob
 */
public class Facturacion extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */

    public Facturacion() {
        initComponents();
        
        //El array de los JLabels
        JLabel[] labels = {LogoCicloTEC, FacturacionLogo,FondoFactura,
        FondoRecibido,FondoSubtotal,FondoDetalle,FondoImpuesto,FondoTotal};
        
        //Ponerle color JLabel del fondo (Gris Oscuro)
        Color col = new Color(152, 151, 153);
        getContentPane().setBackground(col);
        
        //Nuevo código para ajustar muchos JLabels usando arrays!
        for (JLabel label : labels){
            Utilidades.imageStretcher(label);
        }
        
        //Activar esta línea hasta el final
        Utilidades.setCustomIcon(this, "images/CicloTEC Logo.png");
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoCicloTEC = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        FacturacionLogo = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();
        LineaHorizontal1 = new javax.swing.JLabel();
        LineaHorizontal2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        NoFactura = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        FechaRec = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        Impuesto = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Detalle = new javax.swing.JLabel();
        TextoFactura = new javax.swing.JLabel();
        TextoTotal = new javax.swing.JComboBox<>();
        TextFieldRecibido = new javax.swing.JTextField();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        TextoSubtotal = new javax.swing.JLabel();
        TextoImpuesto = new javax.swing.JLabel();
        Texto1 = new javax.swing.JLabel();
        TextFieldDetalle = new javax.swing.JTextField();
        FondoFactura = new javax.swing.JLabel();
        FondoRecibido = new javax.swing.JLabel();
        FondoSubtotal = new javax.swing.JLabel();
        FondoImpuesto = new javax.swing.JLabel();
        FondoTotal = new javax.swing.JLabel();
        FondoDetalle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Facturación - CicloTEC");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(690, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoCicloTEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CicloTEC (Tienda).png"))); // NOI18N
        LogoCicloTEC.setText("jLabel4");
        getContentPane().add(LogoCicloTEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 100));

        Registro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        Registro.setForeground(new java.awt.Color(51, 51, 51));
        Registro.setText("Facturación");
        getContentPane().add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        FacturacionLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Facturación.png"))); // NOI18N
        getContentPane().add(FacturacionLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, 60));

        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Vertical.png"))); // NOI18N
        getContentPane().add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 10, 390));

        LineaHorizontal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Horizontal.png"))); // NOI18N
        getContentPane().add(LineaHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, -1));

        LineaHorizontal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Horizontal.png"))); // NOI18N
        getContentPane().add(LineaHorizontal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        Back.setBackground(new java.awt.Color(217, 217, 217));
        Back.setForeground(new java.awt.Color(51, 51, 51));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrow Curved - Left.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 50, 50));

        Buscar.setBackground(new java.awt.Color(217, 217, 217));
        Buscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Buscar.setForeground(new java.awt.Color(51, 51, 51));
        Buscar.setText("Buscar");
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, 40));

        Agregar.setBackground(new java.awt.Color(217, 217, 217));
        Agregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Agregar.setForeground(new java.awt.Color(51, 51, 51));
        Agregar.setText("Agregar");
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 130, 40));

        Modificar.setBackground(new java.awt.Color(217, 217, 217));
        Modificar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Modificar.setForeground(new java.awt.Color(51, 51, 51));
        Modificar.setText("Anular");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 130, 40));

        NoFactura.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        NoFactura.setForeground(new java.awt.Color(51, 51, 51));
        NoFactura.setText("No. Factura:");
        getContentPane().add(NoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        Cliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        Cliente.setForeground(new java.awt.Color(51, 51, 51));
        Cliente.setText("Cliente:");
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        FechaRec.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        FechaRec.setForeground(new java.awt.Color(51, 51, 51));
        FechaRec.setText("Fecha de Recibido:");
        getContentPane().add(FechaRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        Estado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        Estado.setForeground(new java.awt.Color(51, 51, 51));
        Estado.setText("Estado:");
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        Subtotal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        Subtotal.setForeground(new java.awt.Color(51, 51, 51));
        Subtotal.setText("Subtotal:");
        getContentPane().add(Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        Impuesto.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        Impuesto.setForeground(new java.awt.Color(51, 51, 51));
        Impuesto.setText("Impuesto:");
        getContentPane().add(Impuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        Total.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        Total.setForeground(new java.awt.Color(51, 51, 51));
        Total.setText("Total:");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        Detalle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 22)); // NOI18N
        Detalle.setForeground(new java.awt.Color(51, 51, 51));
        Detalle.setText("Detalle:");
        getContentPane().add(Detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        TextoFactura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextoFactura.setText("...");
        getContentPane().add(TextoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        TextoTotal.setBackground(new java.awt.Color(217, 217, 217));
        TextoTotal.setForeground(new java.awt.Color(51, 51, 51));
        TextoTotal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Búsqueda por nombre-" }));
        getContentPane().add(TextoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 330, 30));

        TextFieldRecibido.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldRecibido.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldRecibido.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldRecibido.setBorder(null);
        TextFieldRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRecibidoActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 210, 20));

        ComboBoxEstado.setBackground(new java.awt.Color(217, 217, 217));
        ComboBoxEstado.setForeground(new java.awt.Color(51, 51, 51));
        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válido", "Anulado" }));
        getContentPane().add(ComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 330, 30));

        TextoSubtotal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextoSubtotal.setText("...");
        getContentPane().add(TextoSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        TextoImpuesto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextoImpuesto.setText("...");
        getContentPane().add(TextoImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        Texto1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Texto1.setText("...");
        getContentPane().add(Texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        TextFieldDetalle.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldDetalle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldDetalle.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldDetalle.setBorder(null);
        getContentPane().add(TextFieldDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 320, 20));

        FondoFactura.setForeground(new java.awt.Color(51, 51, 51));
        FondoFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 280, 40));

        FondoRecibido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 220, 30));

        FondoSubtotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 320, 30));

        FondoImpuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 310, 30));

        FondoTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 350, 30));

        FondoDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        MenuPrincipal jfmain = new MenuPrincipal();
        jfmain.show(); //Mostrar MenuPrincipal
        dispose(); //Cerrar Facturacion
    }//GEN-LAST:event_BackActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    private void TextFieldRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRecibidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRecibidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Back;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Cliente;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JLabel Detalle;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel FacturacionLogo;
    private javax.swing.JLabel FechaRec;
    private javax.swing.JLabel FondoDetalle;
    private javax.swing.JLabel FondoFactura;
    private javax.swing.JLabel FondoImpuesto;
    private javax.swing.JLabel FondoRecibido;
    private javax.swing.JLabel FondoSubtotal;
    private javax.swing.JLabel FondoTotal;
    private javax.swing.JLabel Impuesto;
    private javax.swing.JLabel Linea;
    private javax.swing.JLabel LineaHorizontal1;
    private javax.swing.JLabel LineaHorizontal2;
    private javax.swing.JLabel LogoCicloTEC;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel NoFactura;
    private javax.swing.JLabel Registro;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JTextField TextFieldDetalle;
    private javax.swing.JTextField TextFieldRecibido;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel TextoFactura;
    private javax.swing.JLabel TextoImpuesto;
    private javax.swing.JLabel TextoSubtotal;
    private javax.swing.JComboBox<String> TextoTotal;
    private javax.swing.JLabel Total;
    // End of variables declaration//GEN-END:variables
}
