/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bicis.test.ui;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author gabob
 */
public class RegistroDeServicios extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */

    public RegistroDeServicios() {
        initComponents();
        
        //El array de los JLabels
        JLabel[] labels = {LogoCicloTEC, ServiciosLogo,FondoCodigoServicio,
        FondoMarcaBici,FondoFechaRecibido,FondoPrecio,
        FondoFechaEntrega, FondoObservaciones};
        
        //Ponerle color JLabel del fondo (Gris Oscuro)
        Color col = new Color(152, 151, 153);
        getContentPane().setBackground(col);
        
        //Nuevo código para ajustar muchos JLabels usando arrays!
        for (JLabel label : labels){
            Utilidades.imageStretcher(label);
        }
        
        //Activar esta línea hasta el final
        Utilidades.setCustomIcon(this, "images/CicloTEC Logo.png");
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoCicloTEC = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        Servicios = new javax.swing.JLabel();
        ServiciosLogo = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();
        LineaHorizontal1 = new javax.swing.JLabel();
        LineaHorizontal2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        CodigoServicio = new javax.swing.JLabel();
        CodigoCliente = new javax.swing.JLabel();
        MarcaBicicleta = new javax.swing.JLabel();
        Descripción = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        FechaRecibido = new javax.swing.JLabel();
        FechaEntrega = new javax.swing.JLabel();
        Observaciones = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        TextoCodigoServicio = new javax.swing.JLabel();
        ComboBoxCliente = new javax.swing.JComboBox<>();
        TextFieldMarcaBici = new javax.swing.JTextField();
        jScrollPaneDescripcion = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TextFieldPrecio = new javax.swing.JTextField();
        TextFieldFechaRecibido = new javax.swing.JTextField();
        TextFieldFechaEntrega = new javax.swing.JTextField();
        TextFieldObservacion = new javax.swing.JTextField();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        FondoCodigoServicio = new javax.swing.JLabel();
        FondoMarcaBici = new javax.swing.JLabel();
        FondoPrecio = new javax.swing.JLabel();
        FondoFechaRecibido = new javax.swing.JLabel();
        FondoFechaEntrega = new javax.swing.JLabel();
        FondoObservaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Servicios - CicloTEC");
        setMinimumSize(new java.awt.Dimension(690, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoCicloTEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CicloTEC (Tienda).png"))); // NOI18N
        LogoCicloTEC.setText("jLabel4");
        getContentPane().add(LogoCicloTEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 100));

        Registro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        Registro.setForeground(new java.awt.Color(51, 51, 51));
        Registro.setText("Registro de");
        getContentPane().add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        Servicios.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        Servicios.setForeground(new java.awt.Color(51, 51, 51));
        Servicios.setText("Servicios");
        getContentPane().add(Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        ServiciosLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Servicios.png"))); // NOI18N
        getContentPane().add(ServiciosLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 60));

        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Vertical.png"))); // NOI18N
        getContentPane().add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 10, 390));

        LineaHorizontal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Horizontal.png"))); // NOI18N
        getContentPane().add(LineaHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, -1));

        LineaHorizontal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Línea Horizontal.png"))); // NOI18N
        getContentPane().add(LineaHorizontal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        Back.setBackground(new java.awt.Color(217, 217, 217));
        Back.setForeground(new java.awt.Color(51, 51, 51));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrow Curved - Left.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 50, 50));

        Agregar.setBackground(new java.awt.Color(217, 217, 217));
        Agregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Agregar.setForeground(new java.awt.Color(51, 51, 51));
        Agregar.setText("Agregar");
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 120, 30));

        Buscar.setBackground(new java.awt.Color(217, 217, 217));
        Buscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Buscar.setForeground(new java.awt.Color(51, 51, 51));
        Buscar.setText("Buscar");
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 120, 30));

        Modificar.setBackground(new java.awt.Color(217, 217, 217));
        Modificar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Modificar.setForeground(new java.awt.Color(51, 51, 51));
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 120, 30));

        Eliminar.setBackground(new java.awt.Color(217, 217, 217));
        Eliminar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(81, 18, 18));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 120, 30));

        CodigoServicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        CodigoServicio.setForeground(new java.awt.Color(51, 51, 51));
        CodigoServicio.setText("Código del Servicio:");
        getContentPane().add(CodigoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        CodigoCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        CodigoCliente.setForeground(new java.awt.Color(51, 51, 51));
        CodigoCliente.setText("Código del Cliente:");
        getContentPane().add(CodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        MarcaBicicleta.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        MarcaBicicleta.setForeground(new java.awt.Color(51, 51, 51));
        MarcaBicicleta.setText("Marca de la Bicicleta:");
        getContentPane().add(MarcaBicicleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        Descripción.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        Descripción.setForeground(new java.awt.Color(51, 51, 51));
        Descripción.setText("Descripción:");
        getContentPane().add(Descripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        Precio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        Precio.setForeground(new java.awt.Color(51, 51, 51));
        Precio.setText("Precio:");
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        FechaRecibido.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        FechaRecibido.setForeground(new java.awt.Color(51, 51, 51));
        FechaRecibido.setText("Fecha de Recibido:");
        getContentPane().add(FechaRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        FechaEntrega.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        FechaEntrega.setForeground(new java.awt.Color(51, 51, 51));
        FechaEntrega.setText("Fecha de Entrega:");
        getContentPane().add(FechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        Observaciones.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        Observaciones.setForeground(new java.awt.Color(51, 51, 51));
        Observaciones.setText("Observaciones:");
        getContentPane().add(Observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        Estado.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        Estado.setForeground(new java.awt.Color(51, 51, 51));
        Estado.setText("Estado:");
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        TextoCodigoServicio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        TextoCodigoServicio.setText("...");
        getContentPane().add(TextoCodigoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        ComboBoxCliente.setBackground(new java.awt.Color(217, 217, 217));
        ComboBoxCliente.setForeground(new java.awt.Color(51, 51, 51));
        ComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Búsqueda por Nombre-" }));
        getContentPane().add(ComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 280, -1));

        TextFieldMarcaBici.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldMarcaBici.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        TextFieldMarcaBici.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldMarcaBici.setBorder(null);
        getContentPane().add(TextFieldMarcaBici, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 250, 20));

        jTextArea1.setBackground(new java.awt.Color(217, 217, 217));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneDescripcion.setViewportView(jTextArea1);

        getContentPane().add(jScrollPaneDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 330, -1));

        TextFieldPrecio.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldPrecio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldPrecio.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldPrecio.setBorder(null);
        getContentPane().add(TextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 360, 20));

        TextFieldFechaRecibido.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldFechaRecibido.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldFechaRecibido.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldFechaRecibido.setBorder(null);
        getContentPane().add(TextFieldFechaRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 270, 20));

        TextFieldFechaEntrega.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldFechaEntrega.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldFechaEntrega.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldFechaEntrega.setBorder(null);
        getContentPane().add(TextFieldFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 280, 20));

        TextFieldObservacion.setBackground(new java.awt.Color(217, 217, 217));
        TextFieldObservacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TextFieldObservacion.setForeground(new java.awt.Color(51, 51, 51));
        TextFieldObservacion.setBorder(null);
        getContentPane().add(TextFieldObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 300, 20));

        ComboBoxEstado.setBackground(new java.awt.Color(217, 217, 217));
        ComboBoxEstado.setForeground(new java.awt.Color(51, 51, 51));
        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abierto", "Cerrado" }));
        getContentPane().add(ComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 360, -1));

        FondoCodigoServicio.setForeground(new java.awt.Color(51, 51, 51));
        FondoCodigoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoCodigoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 280, 30));

        FondoMarcaBici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoMarcaBici, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 270, 30));

        FondoPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 380, 30));

        FondoFechaRecibido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoFechaRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 290, 30));

        FondoFechaEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, 30));

        FondoObservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Campo a llenar.png"))); // NOI18N
        getContentPane().add(FondoObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        MenuPrincipal jfmain = new MenuPrincipal();
        jfmain.show(); //Mostrar MenuPrincipal
        dispose(); //Cerrar RegistroDeServicios
    }//GEN-LAST:event_BackActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Back;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel CodigoCliente;
    private javax.swing.JLabel CodigoServicio;
    private javax.swing.JComboBox<String> ComboBoxCliente;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JLabel Descripción;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel FechaEntrega;
    private javax.swing.JLabel FechaRecibido;
    private javax.swing.JLabel FondoCodigoServicio;
    private javax.swing.JLabel FondoFechaEntrega;
    private javax.swing.JLabel FondoFechaRecibido;
    private javax.swing.JLabel FondoMarcaBici;
    private javax.swing.JLabel FondoObservaciones;
    private javax.swing.JLabel FondoPrecio;
    private javax.swing.JLabel Linea;
    private javax.swing.JLabel LineaHorizontal1;
    private javax.swing.JLabel LineaHorizontal2;
    private javax.swing.JLabel LogoCicloTEC;
    private javax.swing.JLabel MarcaBicicleta;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Observaciones;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Registro;
    private javax.swing.JLabel Servicios;
    private javax.swing.JLabel ServiciosLogo;
    private javax.swing.JTextField TextFieldFechaEntrega;
    private javax.swing.JTextField TextFieldFechaRecibido;
    private javax.swing.JTextField TextFieldMarcaBici;
    private javax.swing.JTextField TextFieldObservacion;
    private javax.swing.JTextField TextFieldPrecio;
    private javax.swing.JLabel TextoCodigoServicio;
    private javax.swing.JScrollPane jScrollPaneDescripcion;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
